# -*- coding: utf-8 -*-

from . import test_account_move_invoice_line
from . import test_account_move_fiscal_position
from . import test_account_move_payment_terms
from . import test_account_move_analytic
from . import test_account_move_cash_rounding
from . import test_account_move_multi_currency
from . import test_account_move_multi_company
from . import test_account_move_taxes
from . import test_account_move_journal_sequencing
from . import test_account_move_misc
from . import test_account_move_reversal_wizard
from . import test_account_journal
from . import test_account_account
from . import test_account_tax
from . import test_account_analytic
from . import test_account_payment
from . import test_account_bank_statement
from . import test_account_move_partner_count
from . import test_account_invoice_report
from . import test_account_journal_dashboard
from . import test_control_journal_account
from . import test_fiscal_position
from . import test_reconciliation
from . import test_search
from . import test_settings
from . import test_tax
from . import test_invoice_taxes
from . import test_templates_consistency
from . import test_account_fiscal_year
from . import test_account_all_l10n
from . import test_reconciliation_matching_rules
from . import test_account_onboarding
from . import test_portal_attachment
from . import test_tax_report
from . import test_transfer_wizard
from . import test_account_incoming_supplier_invoice
from . import test_account_payment_register
