# Part of Odoo. See LICENSE file for full copyright and licensing details.

from odoo import models


class AccountMove(models.Model):
    _inherit = "account.move"

    def _l10n_in_is_process_thru_irn(self):
        self.ensure_one()
        """ E-way Bill is not generated by IRN for document types of Debit Note and Credit Note."""
        if self.move_type == "out_refund" or self.debit_origin_id:
            return False
        return bool(
        	self.edi_document_ids.filtered(lambda i: i.edi_format_id.code == "in_einvoice_1_03" and i.state in ("sent", "to_send"))
        )
        
