import base64
import json
import logging
import pytz
import re
from datetime import datetime
from itertools import starmap
from psycopg2 import OperationalError

from odoo import _, api, fields, models
from odoo.exceptions import UserError
from odoo.addons.l10n_in_ewaybill.tools.ewaybill_api import EWayBillApi, EWayBillError


_logger = logging.getLogger(__name__)


class Ewaybill(models.Model):
    _inherit = "l10n.in.ewaybill"

    def _compute_is_process_thru_irn(self):
        for ewaybill in self:
            account_move_id = ewaybill.account_move_id
            """ E-way Bill is not generated by IRN for document types of Debit Note and Credit Note."""
            if not (self.move_type == "out_refund" or self.debit_origin_id):
                ewaybill.is_process_thru_irn = bool(
                    account_move_id.edi_document_ids.filtered(lambda i: i.edi_format_id.code == "in_einvoice_1_03" and i.state in ("sent", "to_send"))
                )

    def _ewaybill_generate_by_irn(self, json_payload):
        if not json_payload.get("Irn"):
            raise EWayBillError({"error": [{
                "code": "waiting",
                "message": _("waiting For IRN generation To create E-waybill")}
            ]})
        if not (token := self.company._l10n_in_edi_get_token()):
            return self._raise_edi_no_config_error()
        params = {
            "auth_token": token,
            "json_payload": json_payload,
        }
        response = self.env['account.edi.format']._l10n_in_edi_connect_to_server(
            url_path="/iap/l10n_in_edi/1/generate_ewaybill_by_irn",
            params=params
        )
        if response.get("error"):
        	error_codes = [error.get("code") for error in response.get("error")]
            if "no-credit" in error_codes:
                e.error_json['odoo_warning'].append({
                    'message': self._ewaybill_get_iap_buy_credits_message()
                })
                raise
            if "1005" in error_codes:
                # Invalid token eror then create new token and send generate request again.
                # This happen when authenticate called from another odoo instance with same credentials (like. Demo/Test)
                self.company_id._l10n_in_edi_authenticate()
                response = self._ewaybill_jsonrpc_to_server(
                    url_path="/iap/l10n_in_edi/1/generate_ewaybill_by_irn",
                    params=params
                )

            if "4002" in error_codes or "4026" in error_codes:
                # Get E-waybill by details in case of IRN is already generated
                # this happens when timeout from the Government portal but E-waybill is generated
                self._ewaybill_get_by_irn(json_payload.get("Irn"))
                response.update({
                    'odoo_warning': [{
                        'message': self.DEFAULT_HELP_MESSAGE % 'generated',
                        'message_post': True
                    }]
                })

	def _ewaybill_generate_irn_json(self):
        return {
            "Irn": self.account_move_id._get_l10n_in_edi_response_json().get("Irn"),
            'Distance': str(self.distance),
            **self._prepare_ewaybill_transportation_json_payload(),
        }

    def _compute_content(self):
        for ewaybill in self:
        	if ewaybill.is_process_thru_irn:
        		ewaybill_json = ewaybill._ewaybill_generate_irn_json()
        		ewaybill.content = base64.b64encode(json.dumps(ewaybill_json).encode())
        return super()._compute_content()

