#!/usr/bin/env python
import sys
if not sys.py3kwarning:
    import os
    os.execvp(sys.executable, [sys.executable, '-3'] + sys.argv)

# set server timezone in UTC before time module imported
__import__('os').environ['TZ'] = 'UTC'
__import__('pkg_resources').declare_namespace('odoo.addons')
import odoo

if __name__ == "__main__":
    odoo.cli.main()
