# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from odoo import _, api, models
from odoo.exceptions import UserError


class MailTemplate(models.Model):
    _inherit = 'mail.template'

    @api.ondelete(at_uninstall=False)
    def _unlink_except_autogenerated(self):
        if self == self.env.ref('portal.mail_template_data_portal_welcome'):
            raise UserError(_("You can't delete this template as it is considered as master data."))
