{
    'name': "Real Estate",
    'author': "Shubham Thanki (shut)",
    'sequence': -100,
    'depends': ['base', 'mail', 'website'],
    'application': True,
    'license': 'LGPL-3',
    'data': [
        # 'security/security.xml',
        'security/ir.model.access.csv',
        'wizard/estate_offer_views.xml',
        'views/estate_property_views.xml',
        'views/estate_property_offer_views.xml',
        'views/estate_property_tag_views.xml',
        'views/estate_property_type_views.xml',
        'views/estate_menus.xml',
        'views/templates.xml',
        'views/res_users_views.xml',
        'report/estate_property_templates.xml',
        'report/estate_property_offer_templates.xml',
        'report/res_users_templates.xml',
        'report/estate_property_reports.xml',
    ],
    'demo': [
        'demo/demo_data.xml',
    ],
    'version': '0.1',
    # 'category': 'Real Estate/Brokerage',
}
