#!/bin/bash
xset s off
xset -dpms

export HOME=/tmp

DISPLAY_URL='http://localhost:8069/point_of_sale/display'

maciotbox=$(/sbin/ifconfig eth0 |grep -Eo ..\(\:..\){5})

if [ -e /home/pi/odoo-remote-server.conf ]
	then
	URL_SERVER=$(grep -r "" /home/pi/odoo-remote-server.conf)/get_url/${maciotbox}
	until wget -q "${URL_SERVER}" -O /dev/null; do 
		var=$((var+1))
		if [ "${var}" == 20 ]
			then
				break
			fi
		sleep 1;

		status_code=$(curl --write-out %{http_code} --silent --output /dev/null ${URL_SERVER})
		if [ "${status_code}" == '200' ]
			then
				if [ "$(curl ${URL_SERVER})" ]
				then
				DISPLAY_URL=$(curl ${URL_SERVER})
				fi
			fi
		done
fi

# wait until odoo is ready, otherwise you will have to plug a
# keyboard into the posbox just to refresh firefox
until wget -q "${DISPLAY_URL}" -O /dev/null ; do sleep 1 ; done


/usr/bin/firefox "${DISPLAY_URL}" &
