#!/bin/bash
xset s off
xset -dpms

export HOME=/tmp

URL_LOCAL='http://localhost:8069/point_of_sale/display'

maciotbox=$(/sbin/ifconfig eth0 |grep -Eo ..\(\:..\){5})

if [ -e /home/pi/odoo-remote-server.conf ]
	then
	URL_SERVER=$(grep -r "" /home/pi/odoo-remote-server.conf)/get_url/${maciotbox}
	until wget -q "${URL_SERVER}" -O /dev/null; do sleep 1; done
	URL_SERVER=$(curl ${URL_SERVER})
	if [ -z "${URL_SERVER}" ];
		then
		DISPLAY_URL=${URL_LOCAL}
		else
		DISPLAY_URL=${URL_SERVER}
		fi
else DISPLAY_URL="${URL_LOCAL}"
fi

# wait until odoo is ready, otherwise you will have to plug a
# keyboard into the posbox just to refresh firefox
until wget -q "${DISPLAY_URL}" -O /dev/null ; do sleep 1 ; done


/usr/bin/firefox "${DISPLAY_URL}" &
